USE [master]
GO

CREATE DATABASE [Ubiquiti-Unifi-Backup]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ubiquiti-Unifi-Backup', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Ubiquiti-Unifi-Backup.mdf' , SIZE = 4375040KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Ubiquiti-Unifi-Backup_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Ubiquiti-Unifi-Backup_log.ldf' , SIZE = 1581696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ubiquiti-Unifi-Backup].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET RECOVERY FULL 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET  MULTI_USER 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET QUERY_STORE = OFF
GO

USE [Ubiquiti-Unifi-Backup]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Ubiquiti-Unifi-Backup] SET  READ_WRITE 
GO


